version: '3.7'

services:
  dev_postgressql:
    image: postgres
    container_name: dev_postgres_postgresql
    environment:
      POSTGRES_PASSWORD: 123456
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_postgres_volume:/var/lib/postgresql/data
