version: '3.7'
volumes:
  database_data:
    driver: local

services:
  dev_postgressql:
    image: postgres
    container_name: dev_postgres_postgresql
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - database_data:/data/postgres
